### ISSUE TITLE
Plugin doesn't work for textfield with autocomplete

### ISSUE THREAD

**Issue by EnidanBri** [RonnyWeiss/APEX-Items-with-APEX-Buttons#1]
I was very happy to find the plugin, because I already use a button attached to an autocomplete field. Until 5.1, I implemented this by putting the button in the HTML Post section of the textfield. But this no longer works in 18.2, therefore I was hoping for you plugin. But unfortunately, it also doesn't work for the autocomplete field (however, works perfectly for normal textfields).

**Comment by RonnyWeiss** [comment]
Hello

Thank for issue report. Please download the latest version. Your bug is fixed in this version.

kind regards

Ronny
